### ISSUE TITLE
the displayed location of IoT Central is inconsistent with other addresses in Azure portal

### ISSUE THREAD

**Issue by czgtest** [VSChina/IoTCentralApp#8]
Run this console application to create IoT Central Resource, then check this IoT Central in Azure Portal,
but find the displayed location is inconsistent with other addresses,  why is it  unitedstates? 

![image](https://user-images.githubusercontent.com/35018765/75013716-cfcc9780-54bf-11ea-8465-6fb54a0ea536.png)

Expect : should be dispaly "United States"
![image](https://user-images.githubusercontent.com/35018765/75020118-0c52c000-54cd-11ea-9424-d27559ede459.png)

**Comment by formulahendry** [comment]
No relation to console application
